kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  client-body-buffer-size: 32M
  hsts: "true"
  proxy-body-size: 1G
  proxy-buffering: "false"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  server-tokens: "false"
  ssl-redirect: "false"
  upstream-keepalive-connections: "50"
  use-proxy-protocol: "true"
labels:
  app: ingress-nginx
name: nginx-configuration
namespace: ingress-nginx
version: v1
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: nginx-ingress
  version: v1
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: nginx-ingress
  version: v1